version: "3.3"
services:
  stirling-pdf:
    image: frooodle/s-pdf:${SOFTWARE_VERSION_TAG}
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - 172.17.0.1:63160:8080
    volumes:
      - ./stirling/latest/data:/usr/share/tessdata:rw
      - ./stirling/latest/config:/configs:rw
      - ./stirling/latest/logs:/logs:rw
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      SECURITY_ENABLELOGIN: "false"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: Stirling-PDF
      UI_HOMEDESCRIPTION: Stirling-PDF
      UI_APPNAMENAVBAR: Stirling-PDF
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "true"
